adapter_name_or_path: saves/Gemma-2-9B/lora/train_2024-09-13-18-07-02
cutoff_len: 925
dataset_dir: data
do_predict: true
eval_dataset: alpaca_spec
finetuning_type: lora
flash_attn: auto
max_new_tokens: 512
max_samples: 100000
model_name_or_path: LLM-Research/gemma-2-9b
output_dir: saves/Gemma-2-9B/lora/eval_2024-09-13-18-07-02
per_device_eval_batch_size: 2
predict_with_generate: true
preprocessing_num_workers: 16
quantization_method: bitsandbytes
stage: sft
temperature: 0.95
template: default
top_p: 0.7
